### ISSUE TITLE
Cannot find module 'await-busboy'

### ISSUE THREAD

**Issue by Aurelsicoko** [koajs/joi-router#36]
In the last commit, some changes have been made but it brokes the router. The dependency `await-busboy` doesn't exist. I used Node v7.0.0 with `--harmony` flag and I ran `npm install` twice.

Thanks for the amazing work on this repository!

```
node --harmony server.js
module.js:474
    throw err;
    ^

Error: Cannot find module 'await-busboy'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/aurelien/repositories/strapi/packages/strapi/node_modules/koa-joi-router/joi-router.js:9:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at require (internal/module.js:20:19)
```

**Comment by aheckmann** [comment]
The branch with this problem is a work in progress and has not been merged or released yet. The open PR states this is an open task. Do not use this branch. https://github.com/koajs/joi-router/pull/35

**Comment by Aurelsicoko** [comment]
Sorry for the inconvenience... I'm using this branch to anticipate Koa2 migration. If you need help, I will glad to contribute. Thanks again for you work!

**Comment by aheckmann** [comment]
No worries. I'll get the missing module published this week which unblocks
the other TODOs. I'm not in a huge rush because Node 7 still requires
passing a V8 flag to enable async/await.
