### ISSUE TITLE
Is there plan to support async/await for handlers in this library?

### ISSUE THREAD

**Issue by martinmicunda** [koajs/joi-router#5]

**Comment by aheckmann** [comment]
Should work?? because it's designed for koa, which supports async/await via
options/flags but I haven't tried it.

**Comment by martinmicunda** [comment]
I have follow code: 

```js
import koa from 'koa';
import router from 'koa-joi-router';
import validator from './lib/validator';
import * as service from './lib/service';

const app = koa();
const api = router();

const routes = [
    {
        method: 'GET',
        path: '/partners/:id',
        validate: validator.findByID,
        handler: async() {
            const respond = await service.findByID(this.params.id);

            this.body = respond.data;
            this.status = respond.statusCode;
        }
    }
];

for(let route of routes) {
    api.route(route);
}
app.use(api.middleware());

export default app;
```
but when I am using `async/await` in handler then I am getting follow error:

```bash
  [ 'AssertionError: route handler must be a GeneratorFunction',
     '    at isGeneratorFunction (/home/vagrant/api/node_modules/koa-joi-router/joi-router.js:149:3)',
     '    at Array.forEach (native)',
     '    at checkHandler (/home/vagrant/api/node_modules/koa-joi-router/joi-router.js:141:23)',
     '    at Router.validateRouteSpec [as _validateRouteSpec] (/home/vagrant/api/node_modules/koa-joi-router/joi-router.js:127:3)',
     '    at Router.route (/home/vagrant/api/node_modules/koa-joi-router/joi-router.js:89:8)',

```

**Comment by aheckmann** [comment]
Ah, open a pull request with the fix + a test and we'll get that in for ya.

**Comment by amcdnl** [comment]
How about KOA2?

**Comment by osenvosem** [comment]
It seems the module do not support Koa2. Any plans to add it?

**Comment by aheckmann** [comment]
I've got a branch going and plan to finish it up before Node 7 is released this month.

**Comment by aheckmann** [comment]
[5.0.0 is out](https://github.com/koajs/joi-router/blob/master/History.md#500--2017-03-09) with async/await support
